### ISSUE TITLE
API PROBLEMS

### ISSUE THREAD

**Issue by JasGH** [kerasus/soalaa#827]
address :  /api/v2/user/219548/orders 
برخی از کلید های ریسپانس این ریکوئست به صورت دو استاندار camel case یا kebab case  تعریف نشده اند.
 مثال :  paymentstatus

![image](https://user-images.githubusercontent.com/81778219/187069967-0049f566-039f-41ae-b719-89ff68d505ac.png)

**Comment by Nima0mr** [comment]
Ticket API Problems {
  - api product selection ( index.vue )
  - api role selection ( index.vue )
  -api for reporting supporter
  -api for poduct extention }
