### ISSUE TITLE
صفحه پروفایل

### ISSUE THREAD

**Issue by kerasus** [kerasus/soalaa#855]

**Comment by kerasus** [comment]
https://www.figma.com/file/RlKtD7zASDYp5WfHSoSuw3/Soalaa-Ph2?node-id=2145%3A11336



![Image](https://user-images.githubusercontent.com/29005080/188309761-cd95d0c6-7d76-487e-830b-8c8b6d1bc334.png)

**Comment by MaryamRazmjoo** [comment]
شروع: دوشنبه 14شهریور
زمان تخمینی برای تکمیل تسک:پیاده سازی کلی=> 1روز
تست رفع باگ => 5ساعت

**Comment by MaryamRazmjoo** [comment]
کد درگیر پیچیدگی هایی شد که به نظر کار اضافه می آید بنابراین فعلا از ادامه ی کار منصرف شدم تا با تمرکز به آن رسیدگی کنم.و تسک را همچنان باز میذارم :)
