### ISSUE TITLE
ساخت آزمون-مرحله ۱

### ISSUE THREAD

**Issue by kerasus** [kerasus/soalaa#856]

**Comment by kerasus** [comment]
[ساخت آزمون-مرحله ۱](https://www.figma.com/file/RlKtD7zASDYp5WfHSoSuw3/Soalaa-Ph2?node-id=2120%3A11804)



![Image](https://user-images.githubusercontent.com/29005080/188309784-df27171d-63aa-47e1-8c73-5d1bdc020b29.png)

**Comment by MaryamRazmjoo** [comment]
تسک پروفایل در الویت زمانی بالاتری قرار دارد
