### ISSUE TITLE
ساخت پنل جدید برای optoin جدید با عنوان هدف سوال

### ISSUE THREAD

**Issue by kerasus** [kerasus/soalaa#863]
در قسمت ویژگی های سوال یک بخش جدید با عنوان هدف سوال نیاز هست
http://jira.alaa.tv/browse/SOALA-21
با توجه به اینکه این ویژگی برای ثبت سوال الزامی می باشد، نیاز هست که در صفحه ساخت سوال این آیتم قرار گیرد

**Comment by JasGH** [comment]
این بخش در نمایش سوال و ادیت سوال ناقص است
