### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by Ayhanemoon** [kerasus/soalaa#869]

**Comment by mitraKhm** [comment]
![Image](https://user-images.githubusercontent.com/72399981/190890476-ed23b9ae-48c8-4851-b61a-c447683251a8.png)



ساختار کلی صفحه انجام شده
تغییرات پیش رو : 

- تغییر ساختار ویجت کلی وتقسیم بندی صفحه به چند ویجت
- متد getData

**Comment by mitraKhm** [comment]
![Image](https://user-images.githubusercontent.com/72399981/190891650-2e71b7b2-efaa-449e-911b-8a1925868b3d.png)



![Image](https://user-images.githubusercontent.com/72399981/190891665-2d4eb59b-7121-411c-a91e-0a20e2e3a941.png)

 در این قسمت ها عنوان و عنوان دکمه به صورت هاردکد قرار داده شده است که میبایست در ساختار دیتا بک اند قرارگیرند.
